### ISSUE TITLE
Provide better healthchecks

### ISSUE THREAD

**Issue by oleg-nenashev** [wiremock/wiremock-testcontainers-java#28]
### Proposal

Follow-up to #25. Once https://github.com/wiremock/wiremock/issues/2164 is implemented in WireMock Core and added to the WireMock Docker, it would be nice to adapt the code to use better healthcheck endpoint for newer versions of the container image

**Comment by oleg-nenashev** [comment]
While https://github.com/wiremock/wiremock/issues/2164 is not implemented , as noted by @wallid , we need another health check that would at least verify that the instance can serve some mock endpoints. It will be also useful for any 2.x tests

I suggest the following:

1) If any `withMapping()` method is passed, note that the mappings should be present
2) If so, also verify the response of `/__admin/mappings` and ensure that the response is not null

**Comment by oleg-nenashev** [comment]
Now we can do better healtchecks starting from WireMock 3.0

**Comment by kapishmalik** [comment]
@oleg-nenashev I can take this up

**Comment by oleg-nenashev** [comment]
Go for it

**Comment by kapishmalik** [comment]
started working on the same. I will raise PR in sometime.

**Comment by kapishmalik** [comment]
@oleg-nenashev created PR for the same.
