### ISSUE TITLE
Publish the module to Maven Central

### ISSUE THREAD

**Issue by oleg-nenashev** [wiremock/wiremock-testcontainers-java#56]
### Proposal

Right now we publish the package only to GitHub packages, and it creates confusion. It would be nice to have it published to the default source repository to improve the DevX a bit. Jitpack helps but far from ideal

### References

- https://github.com/wiremock/community/issues/44

**Comment by edeandrea** [comment]
I'll vote a big +1 to this.

**Comment by oleg-nenashev** [comment]
@edeandrea do you need it for Quarkus builds? I know WireMock is being used there, and would be happy to help to streamline the things there. I am a big fan of Quarkus :)

**Comment by edeandrea** [comment]
Well right now not necessarily with Quarkus directly, but I'm working with @shelajev on a Quarkus & Testcontainers talk and we're looking at using wiremock testcontainers in our demo. An not having the binaries in maven central is kind of a pain to be honest.

**Comment by oleg-nenashev** [comment]
All good, demo in https://github.com/wiremock/wiremock-docker/pull/93
