### ISSUE TITLE
Support loading mapping configurations from any classpath location

### ISSUE THREAD

**Issue by sivaprasadreddy** [wiremock/wiremock-testcontainers-java#61]
### Proposal

Currently we can load mapping files by specifying a class relative path as follows:

```
@Container
static WireMockContainer wiremockServer = new WireMockContainer("2.35.0")
            .withMapping("photos-by-album", MyTest.class,  "mocks-config.json");
```

This will look for mocks-config.json file relative to MyTest.class path.

Could you please add support for loading mapping files from any classpath location as follows:

```
@Container
static WireMockContainer wiremockServer = new WireMockContainer("2.35.0")
            .withMapping("photos-by-album", "wiremock/mappings/mocks-config.json");
```

This should load the mappings from `src/test/resouces/wiremock/mappings/mocks-config.json`.

**Comment by edeandrea** [comment]
+1

**Comment by oleg-nenashev** [comment]
I started hacking the API before my vacation, will try to finish it this week

**Comment by oleg-nenashev** [comment]
First bit https://github.com/wiremock/wiremock-testcontainers-java/pull/66 @edeandrea @sivaprasadreddy

**Comment by oleg-nenashev** [comment]
Released in https://github.com/wiremock/wiremock-testcontainers-java/releases/tag/1.0-alpha-7
